[package]
name = "simple-parser"
version = "0.1.0"
authors = ["Yu Chen <yuchen@tsinghua.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parser-macros = { git = "https://github.com/MashPlant/lalr1" }
